services:
  app:
    container_name: subminder_api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
      - DATABASE_DB=subminder
    restart: always

  db:
    image: postgres:15-alpine
    container_name: subminder_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=subminder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: